
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractInstanceWithAddress, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import BetVaultContractArtifactJson from '../target/vault-BetVault.json' with { type: 'json' };
export const BetVaultContractArtifact = loadContractArtifact(BetVaultContractArtifactJson as NoirCompiledContract);


      export type ClaimAuthorized = {
        market_id: FieldLike
nullifier: FieldLike
amount: (bigint | number)
recipient: FieldLike
      }
    

      export type BetPlaced = {
        market_id: FieldLike
outcome: (bigint | number)
amount: (bigint | number)
bet_id: FieldLike
commitment: FieldLike
      }
    

/**
 * Type-safe interface for contract BetVault;
 */
export class BetVaultContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, BetVaultContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, BetVaultContract.artifact, wallet) as Promise<BetVaultContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, token_address: AztecAddressLike, wormhole_address: AztecAddressLike, admin: AztecAddressLike) {
    return new DeployMethod<BetVaultContract>(PublicKeys.default(), wallet, BetVaultContractArtifact, BetVaultContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, token_address: AztecAddressLike, wormhole_address: AztecAddressLike, admin: AztecAddressLike) {
    return new DeployMethod<BetVaultContract>(publicKeys, wallet, BetVaultContractArtifact, BetVaultContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof BetVaultContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<BetVaultContract['methods'][M]>
  ) {
    return new DeployMethod<BetVaultContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      BetVaultContractArtifact,
      BetVaultContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return BetVaultContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(BetVaultContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'processed_bets' | 'used_nullifiers' | 'claimed_commitments' | 'token_address' | 'wormhole_address' | 'admin' | 'user_bets'> {
      return {
        processed_bets: {
      slot: new Fr(1n),
    },
used_nullifiers: {
      slot: new Fr(2n),
    },
claimed_commitments: {
      slot: new Fr(3n),
    },
token_address: {
      slot: new Fr(4n),
    },
wormhole_address: {
      slot: new Fr(6n),
    },
admin: {
      slot: new Fr(8n),
    },
user_bets: {
      slot: new Fr(10n),
    }
      } as ContractStorageLayout<'processed_bets' | 'used_nullifiers' | 'claimed_commitments' | 'token_address' | 'wormhole_address' | 'admin' | 'user_bets'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** authorizeClaim(market_id: field, commitment: field, secret: field, recipient: struct, amount: integer, authwit_nonce: field) */
    authorizeClaim: ((market_id: FieldLike, commitment: FieldLike, secret: FieldLike, recipient: EthAddressLike, amount: (bigint | number), authwit_nonce: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** bet(market_id: field, outcome: integer, amount: integer, commitment: field, bet_id: field, authwit_nonce: field, from: struct) */
    bet: ((market_id: FieldLike, outcome: (bigint | number), amount: (bigint | number), commitment: FieldLike, bet_id: FieldLike, authwit_nonce: FieldLike, from: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(token_address: struct, wormhole_address: struct, admin: struct) */
    constructor: ((token_address: AztecAddressLike, wormhole_address: AztecAddressLike, admin: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** find_bet_for_claim(owner: struct, commitment: field, market_id: field) */
    find_bet_for_claim: ((owner: AztecAddressLike, commitment: FieldLike, market_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_admin() */
    get_admin: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_token_address() */
    get_token_address: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_user_bets(owner: struct, offset: integer, limit: integer) */
    get_user_bets: ((owner: AztecAddressLike, offset: (bigint | number), limit: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_commitment_claimed(commitment: field) */
    is_commitment_claimed: ((commitment: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_nullifier_used(nullifier: field) */
    is_nullifier_used: ((nullifier: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_processed(bet_id: field) */
    is_processed: ((bet_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { ClaimAuthorized: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, BetPlaced: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      ClaimAuthorized: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "market_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "nullifier",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 128
            }
        },
        {
            "name": "recipient",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "BetVault::ClaimAuthorized"
},
        eventSelector: EventSelector.fromString("0xa6c1cbaa"),
        fieldNames: ["market_id","nullifier","amount","recipient"],
      },
BetPlaced: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "market_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "outcome",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 8
            }
        },
        {
            "name": "amount",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 128
            }
        },
        {
            "name": "bet_id",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "commitment",
            "type": {
                "kind": "field"
            }
        }
    ],
    "path": "BetVault::BetPlaced"
},
        eventSelector: EventSelector.fromString("0x4b63da74"),
        fieldNames: ["market_id","outcome","amount","bet_id","commitment"],
      }
    };
  }
  
}
